name: Auto Deploy to Gachon Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH deploy to server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_KEY }}
        script: |
          set -e
          cd ~/Jongp
          git reset --hard origin/main
          git clean -fd
          git pull origin main
          cd frontend
          cp -r dist/* ../backend/src/main/resources/static/
          cd ../backend
          ./gradlew build
          PIDS=$(ps -ef | grep 'parkingmate-0.0.1-SNAPSHOT.jar' | grep -v grep | awk '{print $2}')
          for PID in $PIDS; do
            kill -9 $PID || true
          done
          nohup java -jar build/libs/parkingmate-0.0.1-SNAPSHOT.jar --spring.config.location=file:/home/t25115/backend/config/application.properties > out.log 2>&1 &
